# Generated by Django 3.2.16 on 2023-01-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='inform',
            new_name='desc',
        ),
    ]
